### ISSUE TITLE
Prepare for FileBot 4.8.5

### ISSUE THREAD

**Issue by rednoah** [arch-noob/filebot#1]
Dear @rvasilev, thanks for maintaining the AUR package for `filebot`.

`FileBot 4.8.5` (pre-release, beta) is now available for testing, and includes a new package with pre-built directory structure for Arch Linux:
```
https://get.filebot.net/filebot/FileBot_4.8.5/FileBot_4.8.5-aur.tar.xz
```

* It's currently based on the DEB package, but Gnome / KDE / XDG integration should be exactly the same.
* This package requires `OpenJDK 11` and `OpenJFX 11`. Though Java 8 compatibility builds (same as in the `portable` package) are possible if that makes things easier.

Please let me know if you need any help or support from my side to make FileBot work well on Arch or simplify the build process on your end.

**Comment by rvasilev** [comment]
@rednoah, thank you for notification. I'll try it

**Comment by rednoah** [comment]
Note that the new package is more platform independent, and most dependencies are handled via dependencies.

e.g. on Debian these would be `openjdk-11-jre, openjfx, mediainfo, libchromaprint-tools, p7zip-full, p7zip-rar`

More specifically:
* `java` command
* `openjfx 11` module jars and native libraries
* `libmediainfo` / `libzen` native libraries
* `fpcalc` command
* `7z` command with unrar plugin

**Comment by rvasilev** [comment]
@rednoah , FileBot_4.8.5-aur.tar.xz is jre11 bound. Is there any plan to release official jre8 backport (like FileBot_4.8.5_universal-jdk8.deb)? 
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/filebot/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

```

**Comment by rednoah** [comment]
I can make the `-aur.tar.xz` package a Java 11 or Java 8 build depending on what you prefer / makes your job here easier. The new binary is here to make Arch deployment as easy as possible, so if Java 11 is tricky on Arch, then we'll just go with Java 8. Whichever makes the most sense for the Arch community.

**Comment by rvasilev** [comment]
You're making a tremendous job supporting Filebot for both Java Current and 8. And until Java 8 makes a sense for Arch mainstream, we should go with it.

**Comment by rednoah** [comment]
Alright. I've uploaded new builds and the `FileBot_4.8.5-aur.tar.xz` is now built against `OpenJDK 8`.

**Comment by rednoah** [comment]
Final Release has been pushed:
https://get.filebot.net/filebot/FileBot_4.8.5/
