### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by AptGetGnome** [arch-noob/filebot#10]
Having an issue after just installing filebot, looks fine for a moment but as soon as a button is hovered, only that button shows and the rest of the screen is black, here's a screen shot of the program, the console window and a filebot stats window.

I'm also using filebot on Manjaro x64 for Raspberry Pi 4

![Screenshot_20200923_183446](https://user-images.githubusercontent.com/12438639/93988346-f04d2f00-fdcb-11ea-98dd-4e329f6ec5f1.png)
![Screenshot_20200923_183505](https://user-images.githubusercontent.com/12438639/93988360-f4794c80-fdcb-11ea-9b57-33ea64b7fec3.png)
![Screenshot_20200923_183715](https://user-images.githubusercontent.com/12438639/93988371-f7743d00-fdcb-11ea-811e-e50fd3d34792.png)

**Comment by AptGetGnome** [comment]
Also maybe i should switch to the other java version?

![Screenshot_20200923_184124](https://user-images.githubusercontent.com/12438639/93988718-66ea2c80-fdcc-11ea-8c5d-c4f12f4c374b.png)

**Comment by rvasilev** [comment]
@adamsarin @adamsarin may be, but openjfx for java14 should be also installed. Could you please report here if this will fix the black screen.

**Comment by AptGetGnome** [comment]
@rvasilev just tried, seemed to make no difference.

**Comment by rvasilev** [comment]
@adamsarin @adamsarin I assume that ʼarchlinux-javaʼ was also updated.

@rednoah is there any known reason for black screen after java version update?

**Comment by AptGetGnome** [comment]
@rvasilev yes

**Comment by rednoah** [comment]
Using `-Dsun.java2d.opengl=true` could be a problem on some devices (depending on graphics hardware and driver software).

**Comment by rvasilev** [comment]
@rednoah is this parameter required for most of users or it could be safely removed?

@adamsarin could you check and report if your problem was resolved?

**Comment by AptGetGnome** [comment]
> @rednoah is this parameter required for most of users or it could be safely removed?
> 
> @adamsarin could you check and report if your problem was resolved? 

I'm not 100% on how I'm supposed to specify this parameter, when running it after filebot it says it's not a valid option

**Comment by rvasilev** [comment]
@adamsarin this option is located in  https://github.com/arch-noob/filebot/blob/7bd657800e2edf8ffc8db7e0371620682a1c1efd/filebot-arch.sh#L22 

Or in /usr/bin/filebot, the same line.

**Comment by AptGetGnome** [comment]
> @adamsarin this option is located in  https://github.com/arch-noob/filebot/blob/7bd657800e2edf8ffc8db7e0371620682a1c1efd/filebot-arch.sh#L22 
> 
> Or in /usr/bin/filebot, the same line. 

Perfect! Issue seems to be resolved!

**Comment by rvasilev** [comment]
@adamsarin @rednoah, could this option be removed from installer without negative consequences?

**Comment by rednoah** [comment]
`-Dsun.java2d.opengl=true` is not used in any of the official `filebot.sh` launchers because the Java developers presumably decided to not make it default for some reason. I wouldn't add that option by default.

If the default render pipeline doesn't work, then switching to a different render pipeline via `-Dsun.java2d.opengl=true` can work around issues and make things work. But if there's issue with `-Dsun.java2d.opengl=true`, then using the default might help work around those. Either way, it's not going to work out-of-the-box for a small number of users.

**Comment by AptGetGnome** [comment]
@rvasilev Am i good to close the issue?
