### ISSUE TITLE
Renaming a file

### ISSUE THREAD

**Issue by AptGetGnome** [arch-noob/filebot#11]
Having an issue when i'm renaming files, unsure what exactly the issue is
![Screenshot_20200925_202113](https://user-images.githubusercontent.com/12438639/94256226-d139d300-ff6c-11ea-977d-2ef8fd061409.png)

**Comment by rvasilev** [comment]
https://www.filebot.net/forums/viewtopic.php?t=4018

I have a temptation to update PKGBUILD with the latest java version (14 for now) from arch repository with most current supported OpenJFX.
