### ISSUE TITLE
java version issue

### ISSUE THREAD

**Issue by dwidmann** [arch-noob/filebot#12]
When trying to move files with filebot with the current packaging (4.9.1-6) I got the following error:

>dustin@terra ~> filebot
> MOVE: NoClassDefFoundError: javafx/concurrent/Task
> java.lang.NoClassDefFoundError: javafx/concurrent/Task                                                                                           
> Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task       

The AUR package depends on java-runtime-headless, java-openjfx, fontconfig, and chromaprint ;; the former two seem to install java-openjfx-14.0.2.u0-2 and jre-openjdk-headless-14.0.2.u12-1 at the moment.

I believe the problem is that the filebot package being downloaded (from get.filebot.net) is a java 8 compatibility build that doesn't work with later java versions, e.g., 14. 

>dustin@terra ~> filebot -help
>FileBot 4.9.1 (r7372) JDK8`

I worked around this by using jre8-openjdk-headless, java8-openjfx and running `archlinux-java set java-8-openjdk/jre` before running filebot.

I think this was introduced in a very recent revision of the PKGBUILD, within the last month or so ... I'm not sure which anymore because I cleared my package cache last week, but *I think* 4.9.1-3 still functioned as expected, because I reverted to an older version maybe 2-3 weeks ago because I was having trouble with one of the newer revisions.

**Comment by Motophan** [comment]
would this have the xatter problem?

**Comment by rvasilev** [comment]
@dwidmann Java 8 compatibility source could be a problem, at least it sounds possible for me.

Next version of filebot will be not compatible with java 8.

I'll look into the current version of PKGBUILD to introduce regression for 4.9.1

**Comment by sylvainbx** [comment]
Hi there,

During the update, I received the following messages that, I  guess, are related to this issue:
```
This version of Filebot is using Java 11 or 14  with OpenJFX
so java-8 dependency could be removed.
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/filebot/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
erreur : la commande n’a pas pu être exécutée correctement
```

I was able to workaround it, by removing java8 and reinstalling java 14:
```
sudo pacman -Rs jre8-openjdk
sudo pacman -Rs jdk8-openjdk 
sudo pacman -S jre-openjdk
```

**Comment by rvasilev** [comment]
@sylvainbx Changing active java version to 11+ with archlinux-java may help

**Comment by rednoah** [comment]
The `liberica-jdk-full-bin` package is effectively required now because it's Java 11+ and includes OpenJFX built-in. Making things work with other JRE / JFX providers is possible but difficult.

**Comment by rvasilev** [comment]
@rednoah

Is JDK vendor lock is a right and weighted decision?

**Comment by rvasilev** [comment]
@rednoah `liberica-jdk-full-bin` `Total Installed Size:  466.89 MiB`. Is there any particular reason for JDK and not JRE for regular users?

**Comment by rednoah** [comment]
Is there are JRE-only package? If yes, then that should work just as well.

**Comment by rednoah** [comment]
Well, if you're only using the CLI, then any JDK will probably do fine. But it looks like OpenJFX doesn't work out of the box if it's not a built-in module. It'd be really good if the GUI did work out-of-the-box too.

I do get lots of `java.lang.NoClassDefFoundError: javafx/concurrent/Task` type support requests. Most users prefer things working out-of-the-box rather than having JDK choices. Time is valuable. Disk space is not.
