### ISSUE TITLE
Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 

### ISSUE THREAD

**Issue by Motophan** [arch-noob/filebot#14]
Groovy: 3.0.6
JRE: OpenJDK Runtime Environment 11.0.8
JVM: 64-bit OpenJDK 64-Bit Server VM
CPU/MEM: 4 Core / 3.6 GB Max Memory / 84 MB Used Memory
OS: Linux (amd64)
HW: Linux NAS 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35 +0000 x86_64 GNU/Linux
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/usr/share/java/filebot/groovy.jar) to method sun.nio.fs.UnixFileSystem.getFileStores()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

groovy -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp -Dawt.useSystemAAFontSettings=gasp
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/usr/share/groovy/lib/groovy-2.5.13.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Groovy Version: 2.5.13 JVM: 11.0.8 Vendor: Oracle Corporation OS: Linux

**Comment by rednoah** [comment]
The `filebot.sh` launcher that is included in the `*-aur.tar.xz` binary tarball includes all the recommended standard launcher options, including `--add-opens=java.base/sun.nio.fs=ALL-UNNAMED` which suppresses this particular warning.
