### ISSUE TITLE
Change logic of openjfx modules injection

### ISSUE THREAD

**Issue by rvasilev** [arch-noob/filebot#16]
Current package is creating symlinks, which is fine but quirky.

Next package could inject openjfx directly in `filebot.sh` as referenced in #15

```
# select libjnidispatch.system.so from $(uname -m)-linux-gnu folder
LIBRARY_PATH=$(echo /usr/lib/*-linux-gnu*/jni | tr ' ' ':')
MODULE_PATH=/usr/share/openjfx/lib
```

> We do have a amd64-only package for Debian package as well, but that's different in that it includes JRE/JFX as part of the application bundle and thus doesn't have any external dependencies. I could do that for the aur package as well, but that means amd64 only, which may or may not be a problem for the aur community.

---

```
MODULE_PATH=$(echo /usr/lib/jvm/java-*-openjdk/jmods | tr ' ' ':')
...
java ... --module-path "$MODULE_PATH" ...
```
---

**Comment by rednoah** [comment]
If this is confirmed to work on Arch, then I'll update the `filebot.sh` on my side as well with the proposed changes.

**Comment by rvasilev** [comment]
@rednoah 

All the javafx.* are in `/usr/lib/jvm/java-*-openjdk/lib`

Providing this path as `--module-path "$MODULE_PATH" --add-modules ALL-MODULE-PATH` ends up wit error
```
Error occurred during initialization of boot layer
java.lang.LayerInstantiationException: Package jdk.internal.jimage.decompressor in both module java.base and module jrt.fs
```
looks like modules could be added one-by-one via looping through `ls /usr/lib/jvm/java-*-openjdk/lib/javafx*` and combining separate outputted files to `--add-modules`

**Comment by rvasilev** [comment]
There's reported related issue in `java-openjfx` https://bugs.archlinux.org/task/64121 that was never fixed. Looks like it affects only some applications.

Recommended and known approach is to move javafx modules to another path, but for some reason `openjfx` packagers never did this.

**Comment by rednoah** [comment]
Mhhh. I suppose their approach of just copying the JavaFX modules into the OpenJDK folder makes things more tricky for us here...

**Comment by BlackenedSky84** [comment]
openjfx has been moved to usr/lib/jvm/java-11-openjfx/ after the latest update.

**Comment by rvasilev** [comment]
```
extra/java11-openjfx 11.0.3.u1-1 (64.5 MiB 127.3 MiB) (Installed)
    Java OpenJFX 11 client application platform (open-source implementation of JavaFX)
```
```
❯ ls /usr/lib/jvm
default@  default-runtime@  java-11-openjdk/  java-8-openjdk/
```

@BlackenedSky84 I'm not very sure about this, it could be because of manjaro repo on my side.

**Comment by ShuraEx** [comment]
Since the resent update to openjfx, openjdk, there has been a JavaFX error every time i launch filebot. manually creating sysmlinks to the new openjfx location in /usr/share/filebot does not solve the issue. neither does downgrading java11-openjfx 11.0.3.u1-1 to version 11.0.3.u1-1. 

I have tried editing the filebot.install script to point to the new openjfx location but the install gives out filesystem permission errors. I'm still new to linux and programming so this might have been something I did wrong and didn't understand properly but all i did was change the line for sysmlinks from old to new location so not sure why its giving permission errors. 

For the time being I downgraded openjdk and that seems to work. but hoping for a solution to get it to work with the newer versions of openjfx and openjdk.

Thank You.

**Comment by BlackenedSky84** [comment]
@rvasilev It looks like manjaro is behind the latest on the arch repo is java11-openjfx 11.0.10.u1-1 which could be problematic until manjaro updates it.

@ShuraEx Symlinking the javafx.* files doesn't seem to be enough. I symlinked all files in the /usr/lib/jvm/java-11-openjfx/lib/ dir and it works OK.

**Comment by ShuraEx** [comment]
> @ShuraEx Symlinking the javafx.* files doesn't seem to be enough. I symlinked all files in the /usr/lib/jvm/java-11-openjfx/lib/ dir and it works OK.

@BlackenedSky84 Thank you so much for the solution, I tried as you mentioned and linked everything in /usr/lib/jvm/java-11-openjfx/lib/ and it now works with the newer versions of openjfx and openjdk. I'm still curious as to why the javafx.* symlinks alone weren't enough when they were fine previously. I'm still learning my way around linux and coding and this was very educational.

Thank You again and Have a wonderful day.

**Comment by rvasilev** [comment]
@ShuraEx symlinking `/usr/lib/jvm/java-11-openjfx/lib/` to `/usr/share/filebot/openjfx/` breaks filebot on manjaro host with
```
Error occurred during initialization of boot layer
java.lang.LayerInstantiationException: Package jdk.internal.jimage.decompressor in both module java.base and module jrt.fs
```
which digs to ol'known https://github.com/arch-noob/filebot/issues/16#issuecomment-706269536 and https://github.com/arch-noob/filebot/issues/16#issuecomment-706405707

Should this be some tiny move about Arch v Manjaro incompatibility?

**Comment by ShuraEx** [comment]
Interesting, I'm on Arch and @BlackenedSky84's solution of linking everything resolved the issue for me.

**Comment by BlackenedSky84** [comment]
@rvasilev it looks like the jfx package has been updated on manjaro now so should now be the same as on Arch

**Comment by rvasilev** [comment]
@ShuraEx @BlackenedSky84 should be quirk-fixed as of https://github.com/arch-noob/filebot/commit/a15668f3e3c2c497a51d5bdd90f0efd1795da151

Next package update most probably will proper-fix + remove quirks.
