### ISSUE TITLE
Unrecognized option: --module-path [filebot 5.0.3-1]

### ISSUE THREAD

**Issue by passthesh3ll** [arch-noob/filebot#22]
Hello, I've the latest filebot 5.0.3-1, I installed it from aur.
if I run it in terminal I get this error:
```
Unrecognized option: --module-path
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by rvasilev** [comment]
@evilsh3ll a wild guess: do you have another version of Java installed which is used as default?

**Comment by passthesh3ll** [comment]
I removed all other java versions and I installed only `jdk-openjdk`, now it's working. Thanks
