### ISSUE TITLE
Set _JAVA_AWT_WM_NONREPARENTING=1 to avoid blank / grey filebot window

### ISSUE THREAD

**Issue by zDEFz** [arch-noob/filebot#30]
Reported I need to set env variable _JAVA_AWT_WM_NONREPARENTING=1 to make filebot show up in Wayland - in my case Sway. I know that I won't set it globally as it would have ill effects. So this tweak I applied in my alias and the desktop file.

Author rednoah says: If _JAVA_AWT_WM_NONREPARENTING fixes the issue then so be it. Please report the issue to the AUR package maintainers.

Before:
![image](https://github.com/user-attachments/assets/14b31c8d-2601-4be6-af70-cf49b2f06dd8)

After:
![image](https://github.com/user-attachments/assets/edd6744b-3b3d-4c4b-aad7-2ce71f4607ee)

**Comment by rvasilev** [comment]
@zDEFz 
@rednoah 

It's related to [https://wiki.archlinux.org/title/Java#Gray_window,_applications_not_resizing_with_WM,_menus_immediately_closing]() with more than one solution.

Should there be any check to distinguish if wayland/x11 is running before setting the variable?

**Comment by rednoah** [comment]
AFAIK, this workaround is specifically for wayland in combination with certain window managers. I strongly support a check for "is wayland" or "not is x11" so that we don't inadvertently introduce issues with currently happy x11 users.

**Comment by zDEFz** [comment]
Maybe just grabbing  $XDG_SESSION_TYPE ?

**Comment by zDEFz** [comment]
I pushed a test best-effort PR. Working for me on sway.
