### ISSUE TITLE
Java8 openjfx

### ISSUE THREAD

**Issue by darsor** [arch-noob/filebot#6]
I was getting java ClassNotFoundExceptions until I installed java8-openjfx.

The PKGBUILD lists
* java-openjfx (Java 12)
* jre8-openjdk (Java 8)

as dependencies. I'm guessing we don't want that java version mismatch?

Aside from that, I also had to change
```
/usr/lib/jvm/java-8-openjdk/bin/java -Dsun.java2d.opengl=true -Dunixfs=false -DuseGVFS=false -DuseExtendedFileAttributes=true -DuseCreationDate=false -Djava.net.useSystemProxies=false -Dapplication.deployment=AUR -Dfile.encoding="UTF-8" -Dsun.jnu.encoding="UTF-8" -Djna.nosys=false -Djna.nounpack=true -Dnet.filebot.Archive.extractor="$EXTRACTOR" -Dnet.filebot.AcoustID.fpcalc="fpcalc" -Dapplication.dir=$HOME/.config/filebot -Djava.io.tmpdir=/tmp/filebot -Dapplication.update=skip -Djna.library.path=/usr/share/java/filebot $JAVA_OPTS -cp /usr/share/java/filebot/filebot.jar net.filebot.Main "$@"
```
to
```
/usr/lib/jvm/java-8-openjdk/jre/bin/java -Dsun.java2d.opengl=true -Dunixfs=false -DuseGVFS=false -DuseExtendedFileAttributes=true -DuseCreationDate=false -Djava.net.useSystemProxies=false -Dapplication.deployment=AUR -Dfile.encoding="UTF-8" -Dsun.jnu.encoding="UTF-8" -Djna.nosys=false -Djna.nounpack=true -Dnet.filebot.Archive.extractor="$EXTRACTOR" -Dnet.filebot.AcoustID.fpcalc="fpcalc" -Dapplication.dir=$HOME/.config/filebot -Djava.io.tmpdir=/tmp/filebot -Dapplication.update=skip -Djna.library.path=/usr/share/java/filebot $JAVA_OPTS -cp /usr/share/java/filebot/filebot.jar net.filebot.Main "$@"
```

on line 22 of /usr/bin/filebot in order for it to find the java executable.

**Comment by rvasilev** [comment]
`java-openjfx (Java 12)` replaced with `java8-openjfx`

For me changing `/usr/lib/jvm/java-8-openjdk/bin/java` to `/usr/lib/jvm/java-8-openjdk/jre/bin/java` broke filebot.

**Comment by ryester19** [comment]
> For me changing `/usr/lib/jvm/java-8-openjdk/bin/java` to `/usr/lib/jvm/java-8-openjdk/jre/bin/java` broke filebot.

I needed to make the same changes as darsor in order to get filebot to launch. /usr/lib/jvm/java-8-openjdk/bin/java didn't exist for me either
