### ISSUE TITLE
7-Zip-JBinding

### ISSUE THREAD

**Issue by Motophan** [arch-noob/filebot#7]
FileBot 4.9.1 (r7372) JDK8
JNA Native: 6.1.0
MediaInfo: 20.08
7-Zip-JBinding: net.sf.sevenzipjbinding.SevenZipNativeInitializationException: Failed to load 7z-JBinding: no 7-Zip-JBinding in java.library.path
Chromaprint: 1.5.0
Extended Attributes: java.io.UncheckedIOException: java.nio.file.FileSystemException: /tmp/filebot/xattr.txt: Error writing extended attribute 'net.filebot.metadata': Operation not supported
Unicode Filesystem: OK
Script Bundle: 2020-09-10 (r673)
Groovy: 3.0.3
JRE: OpenJDK Runtime Environment 1.8.0_265
JVM: 64-bit OpenJDK 64-Bit Server VM
CPU/MEM: 4 Core / 3.2 GB Max Memory / 74 MB Used Memory
OS: Linux (amd64)
HW: Linux NAS 5.8.8-arch1-1 #1 SMP PREEMPT Wed, 09 Sep 2020 18:59:45 +0000 x86_64 GNU/Linux
STORAGE: ext4 [/] @ 393 GB | zfs [/mnt/data] @ 66 TB
DATA: /home/gentoo/.config/filebot
Package: AUR
License: FileBot License XXXXXXXX (Valid-Until: 2021-06-18)
Done ヾ(＠⌒ー⌒＠)ノ

I attempted, using yay, to install java-p7zip-binding 

`yay -S java-p7zip-binding `

This failed to compile as it was built for openjdk 7

I have tried setting default java to oracle java 14, openjdk 14, openjdk 11, openjdk 8

**Comment by rvasilev** [comment]
`java-p7zip-binding` is optional, and looks like it's abandoned/unsupported for some time.

**Comment by Motophan** [comment]
Looks like you can link the system 7z using this method https://www.filebot.net/forums/viewtopic.php?t=6311

Is there a way to have your aur automatically enable this?

**Comment by rvasilev** [comment]
@Motophan I'll look at it.

PR is always welcome.
