### ISSUE TITLE
Extended Attributes:

### ISSUE THREAD

**Issue by Motophan** [arch-noob/filebot#8]
FileBot 4.9.1 (r7372) JDK8
JNA Native: 6.1.0
MediaInfo: 20.08
7-Zip-JBinding: net.sf.sevenzipjbinding.SevenZipNativeInitializationException: Failed to load 7z-JBinding: no 7-Zip-JBinding in java.library.path
Execute [fpcalc, -version]
fpcalc version 1.5.0 (FFmpeg Lavc58.91.100 Lavf58.45.100 SwR3.7.100)

Chromaprint: 1.5.0
Write [xattr:net.filebot.metadata] {"@type":"date","value":1600079280088}
Extended Attributes: java.io.UncheckedIOException: java.nio.file.FileSystemException: /tmp/filebot/xattr.txt: Error writing extended attribute 'net.filebot.metadata': Operation not supported
Unicode Filesystem: OK
Script Bundle: 2020-09-10 (r673)
Groovy: 3.0.3
JRE: OpenJDK Runtime Environment 1.8.0_265
JVM: 64-bit OpenJDK 64-Bit Server VM
CPU/MEM: 4 Core / 3.2 GB Max Memory / 86 MB Used Memory
OS: Linux (amd64)
HW: Linux NAS 5.8.8-arch1-1 #1 SMP PREEMPT Wed, 09 Sep 2020 18:59:45 +0000 x86_64 GNU/Linux
STORAGE: ext4 [/] @ 393 GB | zfs [/mnt/data] @ 66 TB
DATA: /home/gentoo/.config/filebot
Package: AUR
License: FileBot License XXXXXXXXX (Valid-Until: 2021-06-18)
Done ヾ(＠⌒ー⌒＠)ノ

The docker container https://hub.docker.com/r/rednoah/filebot/ will work w/ xattr.
My rootfs is 

```lsblk -f
NAME        FSTYPE     FSVER LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINT
sda
├─sda1      zfs_member 5000  tank  7677520755203519424
└─sda9
sdb
├─sdb1      zfs_member 5000  tank  7677520755203519424
└─sdb9
sdc
├─sdc1      zfs_member 5000  tank  7677520755203519424
└─sdc9
sdd
├─sdd1      zfs_member 5000  tank  7677520755203519424
└─sdd9
sde
├─sde1      zfs_member 5000  tank  7677520755203519424
└─sde9
sdf
├─sdf1      zfs_member 5000  tank  7677520755203519424
└─sdf9
sdg
├─sdg1      zfs_member 5000  tank  7677520755203519424
└─sdg9
sdh
├─sdh1      zfs_member 5000  tank  7677520755203519424
└─sdh9
sdi
├─sdi1      zfs_member 5000  tank  7677520755203519424
└─sdi9
sdj
├─sdj1      zfs_member 5000  tank  7677520755203519424
└─sdj9
sdk
├─sdk1      zfs_member 5000  tank  7677520755203519424
└─sdk9
sdl
├─sdl1      zfs_member 5000  tank  7677520755203519424
└─sdl9
nvme1n1
├─nvme1n1p1 vfat       FAT32       4468-FF1A                             450.7M    12% /boot
├─nvme1n1p2 ext4       1.0         5d327599-7e57-4763-ab19-a5634ba73d9b  366.7G    13% /
└─nvme1n1p3 swap       1           9c2908f0-dc86-4977-990b-f4b87fc5a6f2                [SWAP]
nvme0n1
├─nvme0n1p1
└─nvme0n1p9
```

I have tried setting default java to oracle java 14, openjdk 14, openjdk 11, openjdk 8

**Comment by Motophan** [comment]
Something interesting, /tmp/filebot was owned by my user and not root. Permissions were 755. If I chmod 777 the xattr works. Does this help in any way?

**Comment by rednoah** [comment]
Don't worry about it. `xattr` is not supported on all file systems, and just so happens to not be supported on your `/tmp` file system. `xattr` may very well work on other file systems.

Note that the default `filebot.sh` included in the `*-aur.tar.xz` package includes `-Djava.io.tmpdir="$APP_DATA/tmp"` to configure FileBot correctly make this self-test work.
